name: C Language Learning - Build All Chapters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make valgrind
    
    - name: Show compiler information
      run: |
        gcc --version
        make --version
        valgrind --version
    
    - name: Build Chapter 01 - Fundamentals
      run: |
        echo "🔨 Building Chapter 01 - Fundamentals"
        cd "01_Fundamentals/1.2_Development_Environment" && make all && make clean
        cd "../1.3_First_Program" && make all && make clean
    
    - name: Build Chapter 02 - Basic Syntax Structure
      run: |
        echo "🔨 Building Chapter 02 - Basic Syntax Structure"
        cd "02_Basic_Syntax_Structure/2.1_Program_Structure" && make all && make clean
        cd "../2.2_Identifiers_Keywords" && make all && make clean
        cd "../2.3_Tokens" && make all && make clean
    
    - name: Build Chapter 03 - Data Types Variables
      run: |
        echo "🔨 Building Chapter 03 - Data Types Variables"
        cd "03_Data_Types_Variables/3.1_Basic_Data_Types" && make all && make clean
        cd "../3.2_Type_Modifiers" && make all && make clean
        cd "../3.3_Variable_Declaration_Initialization" && make all && make clean
        cd "../3.4_Constants" && make all && make clean
        cd "../3.5_Type_Conversion" && make all && make clean
    
    - name: Build Chapter 04 - Operators
      run: |
        echo "🔨 Building Chapter 04 - Operators"
        cd "04_Operators/4.1_Arithmetic_Operators" && make all && make clean
        cd "../4.2_Relational_Operators" && make all && make clean
        cd "../4.3_Logical_Operators" && make all && make clean
        cd "../4.4_Bitwise_Operators" && make all && make clean
        cd "../4.5_Assignment_Operators" && make all && make clean
        cd "../4.6_Other_Operators" && make all && make clean
        cd "../4.7_Operator_Precedence_Associativity" && make all && make clean
    
    - name: Build Chapter 05 - Control Flow
      run: |
        echo "🔨 Building Chapter 05 - Control Flow"
        cd "05_Control_Flow/5.1_Conditional_Statements" && make all && make clean
        cd "../5.2_Loops" && make all && make clean
        cd "../5.3_Jump_Statements" && make all && make clean
    
    - name: Build Chapter 06 - Functions
      run: |
        echo "🔨 Building Chapter 06 - Functions"
        cd "06_Functions/6.1_Function_Basics" && make all && make clean
        cd "../6.2_Parameters_Arguments" && make all && make clean
        cd "../6.3_Function_Types" && make all && make clean
        cd "../6.4_Advanced_Function_Concepts" && make all && make clean
    
    - name: Build Chapter 07 - Arrays Strings
      run: |
        echo "🔨 Building Chapter 07 - Arrays Strings"
        cd "07_Arrays_Strings/7.1_Arrays" && make all && make clean
        cd "../7.2_Multi_dimensional_Arrays" && make all && make clean
        cd "../7.3_Strings" && make all && make clean
        cd "../7.4_String_Functions" && make all && make clean
    
    - name: Build Chapter 08 - Pointers
      run: |
        echo "🔨 Building Chapter 08 - Pointers"
        cd "08_Pointers/8.1_Pointer_Basics" && make all && make clean
        cd "../8.2_Pointer_Arithmetic" && make all && make clean
        cd "../8.3_Pointers_and_Arrays" && make all && make clean
        cd "../8.4_Pointers_and_Functions" && make all && make clean
        cd "../8.5_Advanced_Pointer_Concepts" && make all && make clean
    
    - name: Build Chapter 09 - Memory Management
      run: |
        echo "🔨 Building Chapter 09 - Memory Management"
        cd "09_Memory_Management/9.1_Memory_Layout" && make all && make clean
        cd "../9.2_Dynamic_Memory_Allocation" && make all && make clean
        cd "../9.3_Memory_Leaks_Debugging" && make all && make clean
    
    - name: Build Chapter 10 - Structures & Unions
      run: |
        echo "🔨 Building Chapter 10 - Structures & Unions"
        cd "10_Structures_Unions/10.1_Structures" && make all && make clean
        cd "../10.2_Pointers_and_Structures" && make all && make clean
        cd "../10.3_Unions" && make all && make clean
        cd "../10.4_Bit_Fields" && make all && make clean
        cd "../10.5_typedef" && make all && make clean
    
    - name: Build Chapter 11 - File Handling
      run: |
        echo "🔨 Building Chapter 11 - File Handling"
        cd "11_File_Handling/11.1_File_Operations" && make all && make clean
        cd "../11.2_File_IO_Functions" && make all && make clean
        cd "../11.3_File_Positioning" && make all && make clean
        cd "../11.4_Command_Line_Arguments" && make all && make clean
    
    - name: Build Chapter 12 - Preprocessor
      run: |
        echo "🔨 Building Chapter 12 - Preprocessor"
        cd "12_Preprocessor/12.1_Preprocessor_Directives" && make all && make clean
        cd "../12.2_Macros" && make all && make clean
        cd "../12.3_Conditional_Compilation" && make all && make clean
        cd "../12.4_Predefined_Macros" && make all && make clean
    
    - name: Build Chapter 13 - Advanced Topics
      run: |
        echo "🔨 Building Chapter 13 - Advanced Topics"
        cd "13_Advanced_Topics/13.1_Complex_Data_Structures" && make all && make clean
        cd "../13.2_Advanced_Pointer_Techniques" && make all && make clean
        cd "../13.3_Bit_Manipulation" && make all && make clean
        cd "../13.4_Variable_Arguments" && make all && make clean
        cd "../13.5_Signal_Handling" && make all && make clean
        cd "../13.6_Multi-file_Programs" && make all && make clean
    
    - name: Build Chapter 14 - Standard Library
      run: |
        echo "🔨 Building Chapter 14 - Standard Library"
        cd "14_Standard_Library/14.1_Standard_IO" && make all && make clean
        cd "../14.2_String_Handling" && make all && make clean
        cd "../14.3_Math_Library" && make all && make clean
        cd "../14.4_Memory_Management" && make all && make clean
        cd "../14.5_Character_Classification" && make all && make clean
        cd "../14.6_Time_Functions" && make all && make clean
    
    - name: Build Chapter 15 - Debugging & Tools
      run: |
        echo "🔨 Building Chapter 15 - Debugging & Tools"
        cd "15_Debugging_Tools/15.1_Debugging_Techniques" && make all && make clean
        cd "../15.2_Common_Errors" && make all && make clean
        cd "../15.3_Development_Tools" && make all && make clean
    
    - name: Run comprehensive test
      run: |
        echo "🧪 Running comprehensive test of all examples"
        # Find all Makefiles and test compilation (excluding master chapter Makefiles)
        find . -name "Makefile" -type f | grep -v "^\.\/[0-9][0-9]_.*\/Makefile$" | while read makefile; do
          dir=$(dirname "$makefile")
          echo "Testing compilation in: $dir"
          cd "$dir"
          make all
          make clean
          cd - > /dev/null
        done
    
    - name: Build summary
      run: |
        echo "✅ Build Summary:"
        echo "📁 Chapters built and tested:"
        echo "  • Chapter 01: Fundamentals (3 sections)"
        echo "  • Chapter 02: Basic Syntax & Structure (3 sections)"
        echo "  • Chapter 03: Data Types & Variables (5 sections)"
        echo "  • Chapter 04: Operators (7 sections)"
        echo "  • Chapter 05: Control Flow (3 sections)"
        echo "  • Chapter 06: Functions (4 sections)"
        echo "  • Chapter 07: Arrays & Strings (4 sections)"
        echo "  • Chapter 08: Pointers (5 sections)"
        echo "  • Chapter 09: Memory Management (3 sections)"
        echo "  • Chapter 10: Structures & Unions (5 sections)"
        echo "  • Chapter 11: File Handling (4 sections)"
        echo "  • Chapter 12: Preprocessor (4 sections)"
        echo "  • Chapter 13: Advanced Topics (6 sections)"
        echo "  • Chapter 14: Standard Library (6 sections)"
        echo "  • Chapter 15: Debugging & Tools (3 sections)"
        echo ""
        echo "🔧 Total examples: 64 working C programs"
        echo "🛠️  All examples compile with: gcc -Wall -Wextra -std=c99 -pedantic"
        echo "✅ All tests passed successfully!"
